### ISSUE TITLE
Create TODO list for contributors?

### ISSUE THREAD

**Issue by joshuawarner32** [dikaiosune/rusl#1]
First, I love this project!

It's something I wouldn't mind throwing a few hours of spare time at, now and again.

Something that would make contributing enormously easier would be to have a list of bite-size tasks that are easy for a newcomer to tackle in an hour or two.

Thoughts?

**Comment by anp** [comment]
Thanks :D !

I will definitely set some time aside for a TODO list (it would help me prioritize my tinkering too). Although be warned that at its current stage the test setup has only been tried on an up-to-date Arch Linux x86_64 install, and that given the various constraints on my time it's highly at risk of becoming abandonware :smile:.

**Comment by bitemyapp** [comment]
@dikaiosune are you alright with triaging/reviewing outside contributions? Want to make sure others aren't just spamming you by PR'ing the repo.

**Comment by anp** [comment]
Sure thing, I just have limited time so PRs would probably wait for a while before review/merge. Just to be very clear though, I'm doing this as a learning exercise/demonstration, not a genuine attempt to supplant musl :smile:.

**Comment by bitemyapp** [comment]
@dikaiosune _shrugs_ learn by doing better.

**Comment by anp** [comment]
It's empty at the moment, but I'll begin populating #6 shortly. Thanks again for your interest!
