### ISSUE TITLE
Clarify goal here

### ISSUE THREAD

**Issue by anp** [dikaiosune/rusl#13]
I'd still like to work on this more, but in light of https://github.com/japaric/steed I think it'd be good to focus on areas of musl where Rust can add value to C programs linked against it, rather than trying to build a C-free std (@japaric has much better follow through than I do!).

@mrhota since you've expressed interest in contributing more actively, I'd be curious to hear your thoughts.

**Comment by mrhota** [comment]
This is a learning experience for me. I'm still interested in porting a libc to Rust just to see what I can learn. I only heard about steed yesterday; I don't have any opinions about it. 🤷‍♂️

**Comment by anp** [comment]
Cool!
